### ISSUE TITLE
Incorrect IOSTANDARD for VGA signals

### ISSUE THREAD

**Issue by zephray** [tomverbeure/panologic#3]
Hi,

Here: 
https://github.com/tomverbeure/panologic/blob/fd46889460c7d02a05b9c22f9c2bd9001452a180/bringup/xilinx/top.ucf#L133

VGA signals and LPDDR address signals share the same IO Bank, thus they are all powered by the same 1.8V power rail. The IOSTANDARD for these VGA signals should be LVCMOS18 rather than LVCMOS33.

LVCMOS18 VGA signals only include those routed to the VGA DAC (R[7:0], G[7:0], B[7:0], BLANK and CLK), and does not include those routed directly to the VGA interface circuit (HS, VS, SCL, and SDA).

By the way, I believe the LPDDR RAM uses LVCMOS18 as well rather than SSTL18_I. DDR use that, while LPDDR does not.

**Comment by zephray** [comment]
Well, for the LPDDR, actually I have tested, the RAM works if I specifiy signals to be LVCMOS18 (including the differential clock), but doesn't work if signals are specified to be SSTL18_I.

**Comment by tomverbeure** [comment]
I don't think it's a huge issue to specify LVCMOS33 instead of LVCMOS18 (in terms of destroying the chip), but I'll definitely fix it for all my projects. And the LPDDR IOs as well.

**Comment by zephray** [comment]
Yes it really doesn’t matter as long as it is connected to the 1.8V power rail in the hardware. I noticed this issue because it told be I am putting 3.3V and 1.8V IO in one IO bank, and refuse to implement the design.

**Comment by tomverbeure** [comment]
Fixed with eb29ce17270e.

Tom
