### ISSUE TITLE
Why use a single port on the USB IC connected to a USB Hub IC. 

### ISSUE THREAD

**Issue by fraser125** [tomverbeure/panologic#5]
I happen to find the reason for this
`Hi-Speed Universal Serial Bus host controller for embedded applications with built-in 3-port HUB. However, for some reason there is a separate 3-port HUB on the board, so I assume that only one port is used. (Why?)`  
  
and thought it might help others.   
  
`if you place the external hub directly on the EHCI adapter card, this guarantees that the lower speed controllers are no longer needed. This dramatically decreased the cost as well as the circuity of the EHCI adapter card.`
  
Refence [http://www.fysnet.net/the_universal_serial_bus.htm](http://www.fysnet.net/the_universal_serial_bus.htm)

**Comment by zephray** [comment]
That's part of the story. The ISP1760 used on the board already integrated a 3-port HUB to mitigate/ workaround the additional lower speed controller requirement in the EHCI. In this case, the user should be able to directly use low-speed/full-speed devices on ISP1760 even though it's a high-speed-only controller. However, the integrated HUB in the ISP1760 was buggy and didn't really work. So an external HUB on the board was used instead to workaround the buggy internal hub.

**Comment by fraser125** [comment]
Just read the datasheet, you are right.  NXP definitely designed the part with a hub to simplify the implementation. 

Maybe the following text:
Hi-Speed Universal Serial Bus host controller for embedded applications with a built-in 3-port HUB. To mitigate one of the controller’s errata a separate 3-port HUB was installed on the board, only exposing one of the hub ports on the ISP1760 through the separate hub SMSC USB2513.

**Comment by tomverbeure** [comment]
I'm a little bit behind on this, but the texts has been updated with commit 6316eeb.

Thanks!
Tom
